version: '3'
services:
  db:
    image: postgres:latest
    container_name: Database
    environment:
      POSTGRES_DB: Financial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"

  backend:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: Financial.API
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DATABASE: Host=db;Database=Financial;Username=postgres;Password=senha
      SECRET: eyJpZCI6IjEiLCJzdWIiOiIxMjM0NTU0MzIxIiwibmFtZSI6Ik5hbWUgTmFtZSBOYW1lIiwiaWF0IjoxNjE1MTYxNTE2MX0